"""
Verifier Agent — independent second-opinion on vulnerability findings.

After the primary VulnAgent flags a candidate, the VerifierAgent re-examines
the same evidence from a skeptical angle:

1. Validates the attack path step by step
2. Checks for false-positive indicators
3. Assigns CVSS-style severity and CWE identifier
4. Produces a VerifiedFinding used to gate PoC generation

Only findings where is_confirmed=True proceed to the PoC generator.
This two-agent architecture significantly reduces noise in the final report.

Prompt caching is applied identically to the primary agent:
  - System prompt        → cached (constant across all verifications)
  - Verification rubric  → cached (static analysis framework)
  - Finding-specific data → NOT cached (unique per finding)
"""

import json
import os
import sys
import time
from dataclasses import dataclass, field, asdict
from typing import Optional

import anthropic

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, "kernelsurgeon"))
from kernel_graph import KernelGraph
from graph_analyzer import CandidateFunction
from context_assembler import ContextPackage
from vuln_agent import VulnerabilityFinding


# ---------------------------------------------------------------------------
# Severity thresholds (CVSS v3 bands)
# ---------------------------------------------------------------------------
SEVERITY_BANDS = [
    (9.0, "CRITICAL"),
    (7.0, "HIGH"),
    (4.0, "MEDIUM"),
    (0.1, "LOW"),
    (0.0, "INFORMATIONAL"),
]


def cvss_to_severity(score: float) -> str:
    for threshold, label in SEVERITY_BANDS:
        if score >= threshold:
            return label
    return "INFORMATIONAL"


@dataclass
class VerifiedFinding:
    """The verifier's verdict on a primary vulnerability finding."""
    # Link to original finding
    candidate_name: str
    candidate_file: str
    candidate_subsystem: str

    # Verifier verdict
    is_confirmed: bool
    false_positive_reason: str          # non-empty when is_confirmed=False

    # Severity classification
    severity: str                       # CRITICAL / HIGH / MEDIUM / LOW / INFORMATIONAL
    cvss_score: float                   # 0.0–10.0
    cwe_id: str                         # e.g. "CWE-122"

    # CVSS vector components (informational)
    attack_vector: str                  # LOCAL / NETWORK / ADJACENT / PHYSICAL
    attack_complexity: str              # LOW / HIGH
    privileges_required: str           # NONE / LOW / HIGH
    user_interaction: str               # NONE / REQUIRED
    exploitability: str                 # HIGH / MEDIUM / LOW (combined assessment)
    impact: str                         # what the attacker gains

    # Narrative
    verification_notes: str
    verifier_confidence: str            # HIGH / MEDIUM / LOW

    # Remediation advice
    remediation: str

    # Raw verifier response
    raw_response: str = ""


class VerifierAgent:
    """
    Independent verification agent for vulnerability findings.

    Uses a deliberately skeptical persona to challenge the primary agent's
    conclusions and eliminate false positives before PoC generation.
    """

    SYSTEM_PROMPT = """\
You are an expert Linux kernel security engineer and vulnerability researcher performing independent verification
of potential vulnerability reports generated by an automated analysis system.

Your role is to evaluate the evidence objectively and determine whether the reported
vulnerability is real.  You should:

- CONFIRM findings backed by concrete evidence: specific code references, valid
  attack paths, demonstrable missing checks, or verifiable race windows.
- REJECT findings that are speculative, rely on incorrect assumptions about kernel
  internals, or describe theoretical issues with no realistic exploitation path.
- If the primary agent provides a detailed, technically sound attack path with
  specific code line references, treat that as STRONG evidence in favor of
  confirmation — do not dismiss it without equally specific counter-evidence.
- Absence of visible mitigations in the provided code should count FOR the
  finding, not against it.  Do not assume mitigations exist unless you can
  point to specific code that implements them.

You are expert in:
- Kernel memory safety (slab allocator, GFP flags, refcounting)
- Synchronisation primitives and their guarantees (spinlocks, mutexes, RCU, seqlocks)
- Userspace ↔ kernel trust boundaries (copy_from_user, access_ok, KASAN, SMEP/SMAP)
- VFS, networking, and driver security models
- CVE triage and CVSS scoring for kernel vulnerabilities
- CWE taxonomy for low-level C vulnerabilities

Be concise, precise, and technical.  Do NOT speculate beyond the evidence provided."""

    # Static verification rubric — cached across all verifications
    _VERIFICATION_RUBRIC = """\
## Independent Verification Session

You are reviewing a vulnerability report from a primary analysis agent.
Apply the following verification checklist rigorously.

### Verification Checklist

**Step 1 — Attack path reachability**
- Is every hop in the alleged attack path actually present in the code?
- Is there an unprivileged userspace path to this function (e.g. via an open
  syscall, ioctl, socket operation)?
- Are there kernel config guards (IS_ENABLED, ifdef MODULE) that may prevent
  the vulnerable code from being compiled?

**Step 2 — Preconditions**
- Does exploitation require special capabilities (CAP_NET_ADMIN, CAP_SYS_ADMIN)?
- Does it require a specific namespace, seccomp profile, or AppArmor context?
- Are there race windows so narrow that exploitation is practically infeasible?

**Step 3 — Existing mitigations**
- Is the alleged overflow region on the stack or heap?  Is KASAN/KFENCE active?
- Are there hardened usercopy checks (hardened_usercopy, __check_object_size)?
- Does the kernel version referenced have existing sanitisation (e.g. fortified
  string functions, bounds-checking memcpy)?

**Step 4 — Impact assessment**
- Confidentiality: can the attacker read arbitrary kernel memory?
- Integrity: can the attacker write to arbitrary kernel memory?
- Availability: can the attacker crash the system (kernel panic / DoS)?
- Privilege escalation: can the attacker gain root or escape a container?

### CVSS v3.1 Scoring Guidance

| Metric | Values |
|--------|--------|
| Attack Vector (AV) | N=Network, A=Adjacent, L=Local, P=Physical |
| Attack Complexity (AC) | L=Low, H=High |
| Privileges Required (PR) | N=None, L=Low, H=High |
| User Interaction (UI) | N=None, R=Required |
| Scope (S) | U=Unchanged, C=Changed |
| Confidentiality (C) | N=None, L=Low, H=High |
| Integrity (I) | N=None, L=Low, H=High |
| Availability (A) | N=None, L=Low, H=High |

### Common CWE Identifiers for Kernel Vulnerabilities

| CWE | Description |
|-----|-------------|
| CWE-119 | Improper restriction of operations within bounds of memory buffer |
| CWE-120 | Buffer copy without checking size of input (classic buffer overflow) |
| CWE-122 | Heap-based buffer overflow |
| CWE-121 | Stack-based buffer overflow |
| CWE-125 | Out-of-bounds read |
| CWE-787 | Out-of-bounds write |
| CWE-416 | Use after free |
| CWE-362 | Concurrent execution (race condition) |
| CWE-190 | Integer overflow or wraparound |
| CWE-843 | Access of resource using incompatible type (type confusion) |
| CWE-476 | NULL pointer dereference |
| CWE-401 | Missing release of memory after effective lifetime |
| CWE-269 | Improper privilege management |

### Required JSON Response Format

Respond ONLY with valid JSON (no prose outside the code block):

```json
{
    "is_confirmed": true,
    "false_positive_reason": "",
    "cvss_score": 7.8,
    "cwe_id": "CWE-122",
    "attack_vector": "LOCAL",
    "attack_complexity": "LOW",
    "privileges_required": "NONE",
    "user_interaction": "NONE",
    "exploitability": "HIGH",
    "impact": "Arbitrary kernel heap write; potential privilege escalation to root",
    "verification_notes": "Attack path validated: sys_write → vfs_write → drv_write → overflow at line 47.  No bounds check on user-supplied count parameter.",
    "verifier_confidence": "HIGH",
    "remediation": "Add bounds check: if (count > sizeof(buf)) return -EINVAL;"
}
```

---
## Finding Under Review

"""

    def __init__(
        self,
        model: str = "claude-sonnet-4-20250514",
    ):
        self.model = model
        self.client = anthropic.Anthropic()
        self._total_api_calls = 0

    def _call_llm(self, finding_context: str) -> str:
        """Call Claude with prompt caching on the static rubric."""
        self._total_api_calls += 1

        system = [{"type": "text", "text": self.SYSTEM_PROMPT,
                   "cache_control": {"type": "ephemeral"}}]

        user_content = [
            # Static verification rubric → cached across all verifications
            {"type": "text", "text": self._VERIFICATION_RUBRIC,
             "cache_control": {"type": "ephemeral"}},
            # Finding-specific data → not cached
            {"type": "text", "text": finding_context},
        ]

        try:
            response = self.client.messages.create(
                model=self.model,
                max_tokens=4096,
                system=system,
                messages=[{"role": "user", "content": user_content}],
            )
            usage = getattr(response, "usage", None)
            if usage and getattr(usage, "cache_read_input_tokens", 0):
                print(f"    [verifier cache] read={usage.cache_read_input_tokens} "
                      f"created={getattr(usage, 'cache_creation_input_tokens', 0)}")
            return response.content[0].text
        except anthropic.APIError as e:
            print(f"    [verifier] API error: {e}")
            return json.dumps({
                "is_confirmed": False,
                "false_positive_reason": f"API error during verification: {e}",
                "cvss_score": 0.0,
                "cwe_id": "unknown",
                "attack_vector": "LOCAL",
                "attack_complexity": "HIGH",
                "privileges_required": "HIGH",
                "user_interaction": "REQUIRED",
                "exploitability": "LOW",
                "impact": "unknown",
                "verification_notes": "Verification failed due to API error.",
                "verifier_confidence": "LOW",
                "remediation": "Manual review required.",
            })

    def _parse_response(self, raw: str) -> dict:
        """Parse JSON from verifier response, handling markdown fences."""
        text = raw
        if "```json" in text:
            start = text.index("```json") + 7
            end = text.find("```", start)
            text = text[start:end] if end != -1 else text[start:]
        elif "```" in text:
            start = text.index("```") + 3
            end = text.find("```", start)
            text = text[start:end] if end != -1 else text[start:]

        try:
            return json.loads(text.strip())
        except json.JSONDecodeError:
            import re
            m = re.search(r'\{[\s\S]*\}', text)
            if m:
                try:
                    return json.loads(m.group())
                except json.JSONDecodeError:
                    pass
            return {
                "is_confirmed": False,
                "false_positive_reason": "Failed to parse verifier response",
                "cvss_score": 0.0,
                "cwe_id": "unknown",
                "attack_vector": "LOCAL",
                "attack_complexity": "HIGH",
                "privileges_required": "HIGH",
                "user_interaction": "REQUIRED",
                "exploitability": "LOW",
                "impact": "unknown",
                "verification_notes": raw[:500],
                "verifier_confidence": "LOW",
                "remediation": "Manual review required.",
            }

    @staticmethod
    def _format_neighbor_context(context_pkg: ContextPackage) -> str:
        """Format caller/callee source snippets for the verifier."""
        sections = []

        callers = getattr(context_pkg, "caller_context", [])
        if callers:
            sections.append("### Caller Functions (functions that call the target)")
            for c in callers[:5]:
                role_tag = f" [{c['security_role']}]" if c.get('security_role', 'none') != 'none' else ""
                sections.append(
                    f"\n**{c['name']}** ({c.get('file_path', '?')}, "
                    f"{c.get('subsystem', '?')}{role_tag}):\n```c\n{c.get('snippet', '')}\n```"
                )

        callees = getattr(context_pkg, "callee_context", [])
        if callees:
            sections.append("\n### Callee Functions (functions the target calls)")
            for c in callees[:5]:
                role_tag = f" [{c['security_role']}]" if c.get('security_role', 'none') != 'none' else ""
                sections.append(
                    f"\n**{c['name']}** ({c.get('file_path', '?')}, "
                    f"{c.get('subsystem', '?')}{role_tag}):\n```c\n{c.get('snippet', '')}\n```"
                )

        return "\n".join(sections) if sections else ""

    def _build_finding_context(
        self, finding: VulnerabilityFinding, context_pkg: ContextPackage
    ) -> str:
        """Build the finding-specific prompt section (not cached)."""
        return f"""\
### Primary Finding Summary

- **Function**: `{finding.candidate_name}`
- **File**: `{finding.candidate_file}`
- **Subsystem**: `{finding.candidate_subsystem}`
- **Vulnerability Score**: {finding.vulnerability_score:.1f}
- **Primary Agent Verdict**: vulnerable={finding.is_vulnerable}, confidence={finding.confidence}
- **Alleged Type**: {finding.vulnerability_type}

### Primary Agent Description

{finding.description}

### Primary Agent Attack Path

{finding.attack_path}

### Primary Agent Check-Bypass Analysis

{finding.check_bypass_analysis}

### Source Code Under Review

```c
{context_pkg.source_code}
```

### Graph Context

- In-degree: {context_pkg.graph_neighborhood.get('in_degree', 0)}
- Out-degree: {context_pkg.graph_neighborhood.get('out_degree', 0)}
- Cross-subsystem callers: {context_pkg.candidate.cross_subsystem_callers}
- Nearby security checks: {context_pkg.graph_neighborhood.get('nearby_check_functions', [])}
- Callers by subsystem: {context_pkg.graph_neighborhood.get('caller_subsystems', {})}

{self._format_neighbor_context(context_pkg)}

Apply the verification checklist above and respond with the required JSON.
"""

    def verify(
        self, finding: VulnerabilityFinding, context_pkg: ContextPackage
    ) -> VerifiedFinding:
        """
        Independently verify a VulnerabilityFinding.

        Returns a VerifiedFinding.  Only findings with is_confirmed=True
        should proceed to PoC generation.
        """
        print(f"\n  [verifier] Reviewing {finding.candidate_name}...")

        finding_context = self._build_finding_context(finding, context_pkg)
        raw = self._call_llm(finding_context)
        parsed = self._parse_response(raw)

        cvss = float(parsed.get("cvss_score", 0.0))
        severity = cvss_to_severity(cvss)

        verified = VerifiedFinding(
            candidate_name=finding.candidate_name,
            candidate_file=finding.candidate_file,
            candidate_subsystem=finding.candidate_subsystem,
            is_confirmed=bool(parsed.get("is_confirmed", False)),
            false_positive_reason=parsed.get("false_positive_reason", ""),
            severity=severity,
            cvss_score=cvss,
            cwe_id=parsed.get("cwe_id", "unknown"),
            attack_vector=parsed.get("attack_vector", "LOCAL"),
            attack_complexity=parsed.get("attack_complexity", "HIGH"),
            privileges_required=parsed.get("privileges_required", "HIGH"),
            user_interaction=parsed.get("user_interaction", "REQUIRED"),
            exploitability=parsed.get("exploitability", "LOW"),
            impact=parsed.get("impact", ""),
            verification_notes=parsed.get("verification_notes", ""),
            verifier_confidence=parsed.get("verifier_confidence", "LOW"),
            remediation=parsed.get("remediation", ""),
            raw_response=raw,
        )

        status = "CONFIRMED" if verified.is_confirmed else "REJECTED"
        print(f"  [verifier] {status}: {verified.severity} "
              f"(CVSS {verified.cvss_score:.1f}, {verified.cwe_id})")
        return verified

    def verify_batch(
        self,
        findings: list[VulnerabilityFinding],
        context_pkgs: dict[str, ContextPackage],
        delay: float = 1.0,
    ) -> list[VerifiedFinding]:
        """Verify a list of findings sequentially with rate-limiting delay."""
        results = []
        for finding in findings:
            pkg = context_pkgs.get(finding.candidate_name)
            if pkg is None:
                print(f"  [verifier] No context package for {finding.candidate_name}, skipping")
                continue
            result = self.verify(finding, pkg)
            results.append(result)
            time.sleep(delay)
        return results
